apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mappings.ambassadorshim.admiralty.io
spec:
  group: ambassadorshim.admiralty.io
  names:
    kind: Mapping
    listKind: MappingList
    plural: mappings
    singular: mapping
  scope: Namespaced
  version: v1alpha1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ambassador-shim-operator-sdk
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ambassador-shim-operator-sdk
  template:
    metadata:
      labels:
        name: ambassador-shim-operator-sdk
    spec:
      containers:
        - name: ambassador-shim-operator-sdk
          image: quay.io/admiralty/ambassador-shim-operator-sdk
          command:
          - ambassador-shim-operator-sdk
          imagePullPolicy: Always
